def test_can_connect(manual_connection):
    manual_connection.connect()  # Throws exception on failure to connect